### PR TITLE
init connection metadata on reconnection

### PR DESCRIPTION
**Pull request by vdiez**
When timeout occurs, new reconnections are not possible (socket is always automatically closed) due to messageid not starting at 0. When socket reconnects, it should be as a new connection from the SMB server perspective.

### CODE REVIEW

**Comment by julien-f** [comment]
Hi,

Thanks for your contribution!

I understand the change for `messageId`, but why for `SessionId` and `ProcessId`?

**Comment by vdiez** [comment]
Hello,

indeed not a must, I just thought that logically makes more sense to treat a reconnection as a totally new connection. I can undo if needed.

Cheers

**Comment by julien-f** [comment]
IMHO it would make sense to generate a new `SessionId` but to keep the same `ProcessId`, what do you think?

**Comment by vdiez** [comment]
This is really more a "political" view, and I ignore what is the most common approach among other smb clients, so your call. I will modify as you prefer.

**Comment by julien-f** [comment]
Let's keep the `ProcessId` then, we'll change it later if it appears I was wrong :wink:

**Comment by vdiez** [comment]
done :)

**Comment by julien-f** [comment]
Thanks!

**Comment by julien-f** [comment]
Published as 0.14.0

**Comment by vdiez** [comment]
excellent, thanks to you!

**Pull request merged**
